"""Alembic baseline migrations build/teardown the full schema for all three
databases, and stay drift-free against the live SQLAlchemy metadata.

CI is SQLite-only (D6); Postgres is exercised manually. The baseline
migrations are autogenerated from the same metadata ``create_all`` uses, so
``upgrade head`` must reproduce every managed table and ``downgrade base``
must drop them all.
"""

from __future__ import annotations

from pathlib import Path

from alembic import command
from alembic.autogenerate import compare_metadata
from alembic.config import Config
from alembic.migration import MigrationContext
from alembic.script import ScriptDirectory
from sqlalchemy import create_engine, inspect

from core.database.identity import IdentityBase
from core.database.models import Base
from core.database.serving_models import ServingBase

_REPO_ROOT = Path(__file__).resolve().parents[1]
_INI = _REPO_ROOT / "alembic.ini"


def _config(name: str, url: str) -> Config:
    cfg = Config(str(_INI), ini_section=name)
    cfg.set_main_option("sqlalchemy.url", url)
    return cfg


def _table_names(url: str) -> set[str]:
    eng = create_engine(url)
    try:
        return set(inspect(eng).get_table_names())
    finally:
        eng.dispose()


def _managed(metadata) -> set[str]:
    return set(metadata.tables)


def test_main_upgrade_head_creates_all_tables(tmp_path):
    url = f"sqlite:///{tmp_path / 'main.db'}"
    command.upgrade(_config("main", url), "head")
    present = _table_names(url)
    assert _managed(Base.metadata) <= present


def test_identity_upgrade_head_creates_all_tables(tmp_path):
    url = f"sqlite:///{tmp_path / 'identity.db'}"
    command.upgrade(_config("identity", url), "head")
    present = _table_names(url)
    assert _managed(IdentityBase.metadata) <= present


def test_serving_upgrade_head_creates_all_tables(tmp_path):
    url = f"sqlite:///{tmp_path / 'serving.db'}"
    command.upgrade(_config("serving", url), "head")
    present = _table_names(url)
    assert _managed(ServingBase.metadata) <= present


def test_main_downgrade_base_drops_all_tables(tmp_path):
    url = f"sqlite:///{tmp_path / 'main.db'}"
    cfg = _config("main", url)
    command.upgrade(cfg, "head")
    command.downgrade(cfg, "base")
    remaining = _table_names(url) - {"alembic_version"}
    assert remaining.isdisjoint(_managed(Base.metadata))


def test_serving_downgrade_base_drops_all_tables(tmp_path):
    url = f"sqlite:///{tmp_path / 'serving.db'}"
    cfg = _config("serving", url)
    command.upgrade(cfg, "head")
    command.downgrade(cfg, "base")
    remaining = _table_names(url) - {"alembic_version"}
    assert remaining.isdisjoint(_managed(ServingBase.metadata))


def _autogen_diff(metadata, url: str):
    eng = create_engine(url)
    try:
        with eng.connect() as conn:
            ctx = MigrationContext.configure(
                conn, opts={"compare_type": True, "target_metadata": metadata}
            )
            return compare_metadata(ctx, metadata)
    finally:
        eng.dispose()


def test_main_create_all_matches_migration_head(tmp_path):
    """No drift: a fresh `upgrade head` leaves an empty autogen diff."""
    url = f"sqlite:///{tmp_path / 'main.db'}"
    command.upgrade(_config("main", url), "head")
    assert _autogen_diff(Base.metadata, url) == []


def test_identity_create_all_matches_migration_head(tmp_path):
    url = f"sqlite:///{tmp_path / 'identity.db'}"
    command.upgrade(_config("identity", url), "head")
    assert _autogen_diff(IdentityBase.metadata, url) == []


def test_serving_create_all_matches_migration_head(tmp_path):
    url = f"sqlite:///{tmp_path / 'serving.db'}"
    command.upgrade(_config("serving", url), "head")
    assert _autogen_diff(ServingBase.metadata, url) == []


def test_main_create_all_then_stamp_head_is_consistent(tmp_path):
    """The SQLite fast-path (`create_all`) + `alembic stamp head` leaves a DB
    Alembic considers current, with no drift against the baseline."""
    url = f"sqlite:///{tmp_path / 'main.db'}"
    eng = create_engine(url)
    try:
        Base.metadata.create_all(eng)
    finally:
        eng.dispose()
    cfg = _config("main", url)
    command.stamp(cfg, "head")

    # No pending migrations and no model↔migration drift.
    script = ScriptDirectory.from_config(cfg)
    head = script.get_current_head()
    eng = create_engine(url)
    try:
        with eng.connect() as conn:
            current = MigrationContext.configure(conn).get_current_revision()
    finally:
        eng.dispose()
    assert current == head
    assert _autogen_diff(Base.metadata, url) == []
