"""baseline_identity

Revision ID: 4670440dc5a5
Revises:
Create Date: 2026-05-29 11:13:56.194394

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4670440dc5a5"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clip_identities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("api_pk", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("api_pk"),
    )
    op.create_table(
        "user_identities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("api_pk", sa.BigInteger(), nullable=True),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("city_name", sa.String(), nullable=True),
        sa.Column("profile_pic_url", sa.String(), nullable=True),
        sa.Column("profile_pic_url_hd", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("api_pk"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_identities")
    op.drop_table("clip_identities")
    # ### end Alembic commands ###
