"""baseline_main

Revision ID: 304eae5267e0
Revises:
Create Date: 2026-05-29 11:13:33.597777

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "304eae5267e0"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cluster_labels",
        sa.Column("embedding_case", sa.String(), nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("validation", sa.String(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("warnings", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("generation_seed", sa.Integer(), nullable=True),
        sa.Column("sampled_clip_ids", sa.JSON(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("embedding_case", "cluster_id"),
    )
    op.create_table(
        "cluster_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("embedding_case", sa.String(), nullable=False),
        sa.Column("umap_n_components", sa.Integer(), nullable=False),
        sa.Column("umap_n_neighbors", sa.Integer(), nullable=False),
        sa.Column("umap_min_dist", sa.Float(), nullable=False),
        sa.Column("umap_metric", sa.String(), nullable=False),
        sa.Column("umap2d_n_neighbors", sa.Integer(), nullable=False),
        sa.Column("umap2d_min_dist", sa.Float(), nullable=False),
        sa.Column("umap2d_metric", sa.String(), nullable=False),
        sa.Column("hdbscan_min_cluster_size", sa.Integer(), nullable=False),
        sa.Column("hdbscan_min_samples", sa.Integer(), nullable=True),
        sa.Column("hdbscan_cluster_selection_method", sa.String(), nullable=False),
        sa.Column("hdbscan_metric", sa.String(), nullable=False),
        sa.Column("random_state", sa.Integer(), nullable=False),
        sa.Column("n_clusters", sa.Integer(), nullable=False),
        sa.Column("noise_ratio", sa.Float(), nullable=False),
        sa.Column("min_size", sa.Integer(), nullable=False),
        sa.Column("median_size", sa.Integer(), nullable=False),
        sa.Column("max_size", sa.Integer(), nullable=False),
        sa.Column("passes_validation", sa.Boolean(), nullable=True),
        sa.Column("dbcv", sa.Float(), nullable=True),
        sa.Column("silhouette", sa.Float(), nullable=True),
        sa.Column("param_plateau_score", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "embedding_case",
            "umap_n_components",
            "umap_n_neighbors",
            "umap_min_dist",
            "umap_metric",
            "umap2d_n_neighbors",
            "umap2d_min_dist",
            "umap2d_metric",
            "hdbscan_min_cluster_size",
            "hdbscan_min_samples",
            "hdbscan_cluster_selection_method",
            "hdbscan_metric",
            "random_state",
            name="uq_cluster_runs_params",
        ),
    )
    op.create_table(
        "stage_state",
        sa.Column("stage_name", sa.String(), nullable=False),
        sa.Column("scope_key", sa.String(), nullable=False),
        sa.Column("data_hash", sa.String(), nullable=False),
        sa.Column("config_hash", sa.String(), nullable=False),
        sa.Column("dependency_hash", sa.String(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("stage_name", "scope_key"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("following_count", sa.Integer(), nullable=True),
        sa.Column("follower_count", sa.Integer(), nullable=True),
        sa.Column("parse_status", sa.String(), nullable=True),
        sa.Column("is_low_plays_median", sa.Boolean(), nullable=True),
        sa.Column("is_not_enough_preprocessed", sa.Boolean(), nullable=True),
        sa.Column("is_not_enough_eligible", sa.Boolean(), nullable=True),
        sa.Column("is_eligible", sa.Boolean(), nullable=True),
        sa.Column("is_selected", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "visualization_clusters",
        sa.Column("embedding_case", sa.String(), nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.Column("cx", sa.Float(), nullable=False),
        sa.Column("cy", sa.Float(), nullable=False),
        sa.Column("rx", sa.Float(), nullable=False),
        sa.Column("ry", sa.Float(), nullable=False),
        sa.Column("angle", sa.Float(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("embedding_case", "cluster_id"),
    )
    op.create_table(
        "visualizations",
        sa.Column("embedding_case", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("source_hash", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("embedding_case"),
    )
    op.create_table(
        "clips",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("thumbnail_url", sa.String(), nullable=True),
        sa.Column("video_url", sa.String(), nullable=True),
        sa.Column("caption_text", sa.Text(), nullable=True),
        sa.Column("caption_clean", sa.Text(), nullable=True),
        sa.Column("caption_language", sa.Text(), nullable=True),
        sa.Column("caption_translation", sa.Text(), nullable=True),
        sa.Column("comment_count", sa.Integer(), nullable=True),
        sa.Column("reshare_count", sa.Integer(), nullable=True),
        sa.Column("like_count", sa.Integer(), nullable=True),
        sa.Column("play_count", sa.Integer(), nullable=True),
        sa.Column("video_duration", sa.Float(), nullable=True),
        sa.Column("taken_at", sa.BigInteger(), nullable=True),
        sa.Column("speech_transcription", sa.Text(), nullable=True),
        sa.Column("speech_language", sa.String(), nullable=True),
        sa.Column("speech_confidence", sa.Float(), nullable=True),
        sa.Column("speech_avg_logprob", sa.Float(), nullable=True),
        sa.Column("speech_compression_ratio", sa.Float(), nullable=True),
        sa.Column("is_speech_detected", sa.Boolean(), nullable=True),
        sa.Column("speech_translation", sa.Text(), nullable=True),
        sa.Column("is_garbage", sa.Boolean(), nullable=True),
        sa.Column("is_too_short", sa.Boolean(), nullable=True),
        sa.Column("is_too_long", sa.Boolean(), nullable=True),
        sa.Column("is_too_old", sa.Boolean(), nullable=True),
        sa.Column("is_low_percentile", sa.Boolean(), nullable=True),
        sa.Column("is_high_percentile", sa.Boolean(), nullable=True),
        sa.Column("is_preprocessed", sa.Boolean(), nullable=True),
        sa.Column("is_eligible", sa.Boolean(), nullable=True),
        sa.Column("is_selected", sa.Boolean(), nullable=True),
        sa.Column("is_downloaded", sa.Boolean(), nullable=True),
        sa.Column("is_uploaded", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_clusters",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("embedding_case", sa.String(), nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.Column("umap_x", sa.Float(), nullable=False),
        sa.Column("umap_y", sa.Float(), nullable=False),
        sa.Column("centrality", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "embedding_case"),
        sa.UniqueConstraint(
            "user_id", "embedding_case", name="uq_user_clusters_user_case"
        ),
    )
    op.create_table(
        "user_embeddings",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("embedding_case", sa.String(), nullable=False),
        sa.Column("embedding", sa.LargeBinary(), nullable=False),
        sa.Column("source_hash", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "embedding_case"),
        sa.UniqueConstraint(
            "user_id", "embedding_case", name="uq_user_embeddings_user_case"
        ),
    )
    op.create_table(
        "user_stats",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("n_clips", sa.Integer(), nullable=True),
        sa.Column("median_plays", sa.Float(), nullable=True),
        sa.Column("mean_plays", sa.Float(), nullable=True),
        sa.Column("max_plays", sa.Integer(), nullable=True),
        sa.Column("min_plays", sa.Integer(), nullable=True),
        sa.Column("mean_log_plays", sa.Float(), nullable=True),
        sa.Column("median_log_plays", sa.Float(), nullable=True),
        sa.Column("log_plays_std", sa.Float(), nullable=True),
        sa.Column("log_plays_mad", sa.Float(), nullable=True),
        sa.Column("top_to_median_plays_ratio", sa.Float(), nullable=True),
        sa.Column("share_of_plays_from_top_clip", sa.Float(), nullable=True),
        sa.Column("median_video_duration", sa.Float(), nullable=True),
        sa.Column("mean_video_duration", sa.Float(), nullable=True),
        sa.Column("oldest_clip_taken_at", sa.BigInteger(), nullable=True),
        sa.Column("newest_clip_taken_at", sa.BigInteger(), nullable=True),
        sa.Column("clip_time_span_days", sa.Float(), nullable=True),
        sa.Column("approx_clips_per_week", sa.Float(), nullable=True),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "visualization_users",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("embedding_case", sa.String(), nullable=False),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.Column("centrality", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "embedding_case"),
        sa.UniqueConstraint(
            "user_id", "embedding_case", name="uq_visualization_users_user_case"
        ),
    )
    op.create_table(
        "audio_mir",
        sa.Column("clip_id", sa.BigInteger(), nullable=False),
        sa.Column("is_mir_extracted", sa.Boolean(), nullable=True),
        sa.Column("is_music_detected", sa.Boolean(), nullable=True),
        sa.Column(
            "mir_error",
            sa.Enum(
                "maest", "effnet", "audio_load", "no_audio_file", name="audio_mir_error"
            ),
            nullable=True,
        ),
        sa.Column("approachability", sa.Float(), nullable=True),
        sa.Column("engagement", sa.Float(), nullable=True),
        sa.Column("danceability", sa.Float(), nullable=True),
        sa.Column("is_aggressive", sa.Boolean(), nullable=True),
        sa.Column("is_happy", sa.Boolean(), nullable=True),
        sa.Column("is_party", sa.Boolean(), nullable=True),
        sa.Column("is_relaxed", sa.Boolean(), nullable=True),
        sa.Column("is_sad", sa.Boolean(), nullable=True),
        sa.Column("is_acoustic", sa.Boolean(), nullable=True),
        sa.Column("is_electronic", sa.Boolean(), nullable=True),
        sa.Column("is_instrumental", sa.Boolean(), nullable=True),
        sa.Column("is_female_voice", sa.Boolean(), nullable=True),
        sa.Column("is_bright_timbre", sa.Boolean(), nullable=True),
        sa.Column("is_tonal", sa.Boolean(), nullable=True),
        sa.Column("genre_labels", sa.String(), nullable=True),
        sa.Column("genre_scores", sa.String(), nullable=True),
        sa.Column("moodtheme_labels", sa.String(), nullable=True),
        sa.Column("moodtheme_scores", sa.String(), nullable=True),
        sa.Column("instrument_labels", sa.String(), nullable=True),
        sa.Column("instrument_scores", sa.String(), nullable=True),
        sa.Column("audio_duration_s", sa.Float(), nullable=True),
        sa.Column("inference_time_ms", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["clip_id"],
            ["clips.id"],
        ),
        sa.PrimaryKeyConstraint("clip_id"),
        sa.UniqueConstraint("clip_id", name="uq_audio_mir_clip"),
    )
    op.create_table(
        "clip_embeddings",
        sa.Column("clip_id", sa.BigInteger(), nullable=False),
        sa.Column("embedding_case", sa.String(), nullable=False),
        sa.Column("embedding", sa.LargeBinary(), nullable=False),
        sa.Column("source_hash", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["clip_id"],
            ["clips.id"],
        ),
        sa.PrimaryKeyConstraint("clip_id", "embedding_case"),
        sa.UniqueConstraint(
            "clip_id", "embedding_case", name="uq_clip_embeddings_clip_case"
        ),
    )
    op.create_table(
        "clip_filter_scratch",
        sa.Column("clip_id", sa.Integer(), nullable=False),
        sa.Column("log_plays", sa.Float(), nullable=True),
        sa.Column("creator_relative_robust_z", sa.Float(), nullable=True),
        sa.Column("is_creator_low_outlier", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["clip_id"],
            ["clips.id"],
        ),
        sa.PrimaryKeyConstraint("clip_id"),
    )
    op.create_table(
        "clip_labels",
        sa.Column("clip_id", sa.BigInteger(), nullable=False),
        sa.Column("label_case", sa.String(), server_default="video", nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("validation", sa.String(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("warnings", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("generation_seed", sa.Integer(), nullable=True),
        sa.Column("source_hash", sa.String(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["clip_id"],
            ["clips.id"],
        ),
        sa.PrimaryKeyConstraint("clip_id", "label_case"),
        sa.UniqueConstraint("clip_id", "label_case", name="uq_clip_labels_clip_case"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("clip_labels")
    op.drop_table("clip_filter_scratch")
    op.drop_table("clip_embeddings")
    op.drop_table("audio_mir")
    op.drop_table("visualization_users")
    op.drop_table("user_stats")
    op.drop_table("user_embeddings")
    op.drop_table("user_clusters")
    op.drop_table("clips")
    op.drop_table("visualizations")
    op.drop_table("visualization_clusters")
    op.drop_table("users")
    op.drop_table("stage_state")
    op.drop_table("cluster_runs")
    op.drop_table("cluster_labels")
    # ### end Alembic commands ###
