"""baseline_serving

Revision ID: 03f0f333b872
Revises:
Create Date: 2026-05-29 11:28:39.536882

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03f0f333b872"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "serving_cluster_label",
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("summary", sa.String(), nullable=False),
        sa.Column("modality", sa.String(), nullable=False),
        sa.Column("taste_signalling_label", sa.String(), nullable=False),
        sa.Column("taste_signalling_description", sa.String(), nullable=False),
        sa.Column("taste_signalling_confidence", sa.String(), nullable=False),
        sa.Column("visibility_orientation_label", sa.String(), nullable=False),
        sa.Column("visibility_orientation_description", sa.String(), nullable=False),
        sa.Column("visibility_orientation_confidence", sa.String(), nullable=False),
        sa.Column("boundary_notes", sa.String(), nullable=False),
        sa.Column("validation", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("run_id", "cluster_id"),
    )
    op.create_table(
        "serving_cluster_label_aesthetic",
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.Column("ord", sa.Integer(), nullable=False),
        sa.Column("tag", sa.String(), nullable=False),
        sa.Column("grounded_in", sa.JSON(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("run_id", "cluster_id", "ord"),
    )
    op.create_table(
        "serving_cluster_label_repertoire",
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.Column("ord", sa.Integer(), nullable=False),
        sa.Column("tag", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("recurrence", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("run_id", "cluster_id", "ord"),
    )
    op.create_table(
        "serving_cluster_label_tooltag",
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("ord", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("run_id", "cluster_id", "kind", "ord"),
    )
    op.create_table(
        "serving_cluster_label_variations",
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.Column("ord", sa.Integer(), nullable=False),
        sa.Column("variation", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("run_id", "cluster_id", "ord"),
    )
    op.create_table(
        "serving_cluster_nearest",
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.Column("ord", sa.Integer(), nullable=False),
        sa.Column("nearest_cluster_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("distance", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("run_id", "cluster_id", "ord"),
    )
    op.create_table(
        "serving_distinctiveness",
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("owner_kind", sa.String(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("ord", sa.Integer(), nullable=False),
        sa.Column("feature", sa.String(), nullable=False),
        sa.Column("cohort_value", sa.Float(), nullable=False),
        sa.Column("baseline_mean", sa.Float(), nullable=False),
        sa.Column("baseline_std", sa.Float(), nullable=False),
        sa.Column("z", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("run_id", "owner_kind", "owner_id", "ord"),
    )
    op.create_table(
        "serving_lang_share",
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("owner_kind", sa.String(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("block", sa.String(), nullable=False),
        sa.Column("ord", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("share", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("run_id", "owner_kind", "owner_id", "block", "ord"),
    )
    op.create_table(
        "serving_run",
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("case", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("details_available", sa.Boolean(), nullable=False),
        sa.Column("manifest_ord", sa.Integer(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_table(
        "serving_user_clip",
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("ord", sa.Integer(), nullable=False),
        sa.Column("clip_id", sa.Integer(), nullable=False),
        sa.Column("shortcode", sa.String(), nullable=True),
        sa.Column("thumbnail_url", sa.String(), nullable=True),
        sa.Column("sentence", sa.String(), nullable=False),
        sa.Column("validation", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("run_id", "user_id", "ord"),
    )
    op.create_table(
        "serving_user_clip_tag",
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("clip_ord", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("ord", sa.Integer(), nullable=False),
        sa.Column("tag", sa.String(), nullable=False),
        sa.Column("evidence", sa.String(), nullable=True),
        sa.Column("grounded_in", sa.JSON(), nullable=True),
        sa.Column("confidence", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("run_id", "user_id", "clip_ord", "kind", "ord"),
    )
    op.create_table(
        "serving_user_clip_warning",
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("clip_ord", sa.Integer(), nullable=False),
        sa.Column("ord", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("run_id", "user_id", "clip_ord", "ord"),
    )
    op.create_table(
        "serving_weighted_tag",
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("owner_kind", sa.String(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("field", sa.String(), nullable=False),
        sa.Column("ord", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("run_id", "owner_kind", "owner_id", "field", "ord"),
    )
    op.create_table(
        "serving_cluster",
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("cx", sa.Float(), nullable=False),
        sa.Column("cy", sa.Float(), nullable=False),
        sa.Column("rx", sa.Float(), nullable=False),
        sa.Column("ry", sa.Float(), nullable=False),
        sa.Column("angle", sa.Float(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("has_detail", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["serving_run.run_id"],
        ),
        sa.PrimaryKeyConstraint("run_id", "cluster_id"),
    )
    op.create_table(
        "serving_cluster_detail",
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("ellipse_cx", sa.Float(), nullable=False),
        sa.Column("ellipse_cy", sa.Float(), nullable=False),
        sa.Column("ellipse_rx", sa.Float(), nullable=False),
        sa.Column("ellipse_ry", sa.Float(), nullable=False),
        sa.Column("ellipse_angle", sa.Float(), nullable=False),
        sa.Column("audio_approachability", sa.Float(), nullable=False),
        sa.Column("audio_engagement", sa.Float(), nullable=False),
        sa.Column("audio_danceability", sa.Float(), nullable=False),
        sa.Column("mood_happy", sa.Float(), nullable=False),
        sa.Column("mood_sad", sa.Float(), nullable=False),
        sa.Column("mood_relaxed", sa.Float(), nullable=False),
        sa.Column("mood_aggressive", sa.Float(), nullable=False),
        sa.Column("mood_party", sa.Float(), nullable=False),
        sa.Column("timbre_acoustic", sa.Float(), nullable=False),
        sa.Column("timbre_electronic", sa.Float(), nullable=False),
        sa.Column("timbre_instrumental", sa.Float(), nullable=False),
        sa.Column("timbre_female_voice", sa.Float(), nullable=False),
        sa.Column("timbre_bright", sa.Float(), nullable=False),
        sa.Column("timbre_tonal", sa.Float(), nullable=False),
        sa.Column("speech_detected_share", sa.Float(), nullable=False),
        sa.Column("caption_detected_share", sa.Float(), nullable=True),
        sa.Column("posting_median_plays", sa.Integer(), nullable=False),
        sa.Column("posting_median_clip_duration_s", sa.Float(), nullable=False),
        sa.Column("posting_median_clips_per_week", sa.Float(), nullable=False),
        sa.Column("posting_engagement_shape_ratio", sa.Float(), nullable=False),
        sa.Column("follower_bucket", sa.String(), nullable=False),
        sa.Column("activity_span_months", sa.Integer(), nullable=True),
        sa.Column("spatial_compactness", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["serving_run.run_id"],
        ),
        sa.PrimaryKeyConstraint("run_id", "cluster_id"),
    )
    op.create_table(
        "serving_run_bounds",
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("min_x", sa.Float(), nullable=False),
        sa.Column("max_x", sa.Float(), nullable=False),
        sa.Column("min_y", sa.Float(), nullable=False),
        sa.Column("max_y", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["serving_run.run_id"],
        ),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_table(
        "serving_user",
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.Column("has_detail", sa.Boolean(), nullable=False),
        sa.Column("centrality", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["serving_run.run_id"],
        ),
        sa.PrimaryKeyConstraint("run_id", "user_id"),
    )
    op.create_table(
        "serving_user_detail",
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column("n_clips", sa.Integer(), nullable=False),
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.Column("audio_approachability", sa.Float(), nullable=False),
        sa.Column("audio_engagement", sa.Float(), nullable=False),
        sa.Column("audio_danceability", sa.Float(), nullable=False),
        sa.Column("mood_happy", sa.Float(), nullable=False),
        sa.Column("mood_sad", sa.Float(), nullable=False),
        sa.Column("mood_relaxed", sa.Float(), nullable=False),
        sa.Column("mood_aggressive", sa.Float(), nullable=False),
        sa.Column("mood_party", sa.Float(), nullable=False),
        sa.Column("timbre_acoustic", sa.Float(), nullable=False),
        sa.Column("timbre_electronic", sa.Float(), nullable=False),
        sa.Column("timbre_instrumental", sa.Float(), nullable=False),
        sa.Column("timbre_female_voice", sa.Float(), nullable=False),
        sa.Column("timbre_bright", sa.Float(), nullable=False),
        sa.Column("timbre_tonal", sa.Float(), nullable=False),
        sa.Column("speech_detected_share", sa.Float(), nullable=False),
        sa.Column("caption_detected_share", sa.Float(), nullable=True),
        sa.Column("posting_median_plays", sa.Integer(), nullable=False),
        sa.Column("posting_median_clip_duration_s", sa.Float(), nullable=False),
        sa.Column("posting_median_clips_per_week", sa.Float(), nullable=False),
        sa.Column("posting_engagement_shape_ratio", sa.Float(), nullable=False),
        sa.Column("follower_bucket", sa.String(), nullable=False),
        sa.Column("activity_span_months", sa.Integer(), nullable=True),
        sa.Column("spatial_distance_from_centroid", sa.Float(), nullable=False),
        sa.Column("spatial_distance_percentile", sa.Integer(), nullable=False),
        sa.Column("spatial_nearest_cluster_id", sa.Integer(), nullable=True),
        sa.Column("spatial_nearest_label", sa.String(), nullable=True),
        sa.Column("spatial_nearest_distance", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["serving_run.run_id"],
        ),
        sa.PrimaryKeyConstraint("run_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("serving_user_detail")
    op.drop_table("serving_user")
    op.drop_table("serving_run_bounds")
    op.drop_table("serving_cluster_detail")
    op.drop_table("serving_cluster")
    op.drop_table("serving_weighted_tag")
    op.drop_table("serving_user_clip_warning")
    op.drop_table("serving_user_clip_tag")
    op.drop_table("serving_user_clip")
    op.drop_table("serving_run")
    op.drop_table("serving_lang_share")
    op.drop_table("serving_distinctiveness")
    op.drop_table("serving_cluster_nearest")
    op.drop_table("serving_cluster_label_variations")
    op.drop_table("serving_cluster_label_tooltag")
    op.drop_table("serving_cluster_label_repertoire")
    op.drop_table("serving_cluster_label_aesthetic")
    op.drop_table("serving_cluster_label")
    # ### end Alembic commands ###
